### ISSUE TITLE
Slow communication

### ISSUE THREAD

**Issue by ilfirin-ms** [fransschreuder/usbpicprog#16]
A have build usbpicprog v0.3hw, used 1.0.4fw and 1.0.5sw.
It's working, but painfully slow, five minutest to load and verify 117kB into PIC18F.
Looking into oscilloscope, clock are 300kHz, and communication is short (1-2ms) bursts of data at 60ms period at writing and even 100ms period at reading.
Is this normal behaviour?

Thank you

**Comment by fransschreuder** [comment]
Hello ilfirin-ms. 
I don't think I have often programmed a 117kB file into an 18F, but this is indeed to be expected if I scale a few seconds for a few kB .hex file to 117kB. 
The PIC in the usbpicprog is not a very fast device, and probably also some of the firmware could be optimized. If you have ideas on how to improve things, your input is welcome.

**Comment by ilfirin-ms** [comment]
fair enough

**Comment by ilfirin-ms** [comment]
Thank you,

I wanted to use it as "independent programmer" for manufacture (to not Windows system), so commercial closed (Asix) and bloated and costy solutions (MPLAB) was not my target.

I did some research also (to build my own programmer based on your design). I would use some modern Arm chip, STM32F072, which has more power and especially, more RAM to buffer data.
Also SPI usage is important for xMHz clock, but there is a catch. I found, there have to be 20ns spaces between commands, data and more commands. This alone will make huge slowdown. Yeah, it could be maybe faster, than your solution, but I feared it wouldn't be manufacture fast enough.

I am also out of time, so probably will not build it. If time allows, I would tried to make 1$_small_F072@48Mhz_16kB_ram version with USB-CDC ascii protocol (don't like idea of making raws usb packets), but also will have slowdown with ascii translation, i know. If it would be not fast enought, port it to 10$_large_F407@168MHz_96kB_ram. If this wouldn't be either fast enough, then I am lost.

**Comment by fransschreuder** [comment]
Hello Mike,
I guess you are not the only one with other priorities. I have little kids now and they take a lot of time, plus a bunch of other projects. 
If somebody with fresh ideas wants to work on usbpicprog, I can make you developer as well, and even give access to the website.
I don't believe the wxWidgets loop is the problem, as the whole hex file is programmed from one while loop that is executed in a thread. There is a huge overhead of the usb library though, and that may cause some of the latency. Most of the latency is caused by the internal usb library of the PIC18F2550. This must take most of the time. Using a larger data buffer would help, but unfortunately I was unable to make this larger than a few bytes (64) or else the firmware became unstable.
Another option is not to use a microcontroller at all, but investigate the speed of the FT2232H chip. It has JTAG, SPI, I2C and some other features as well as raw bitbanging. I don't know at what speed we can bitbang there, but it may be faster than the PIC18F2550.
In that case the PIC code should be ported to the PC application, but I don't see a problem there either.

**Comment by diegoherranz** [comment]
I've been using the FT2232H with OpenOCD and it works quite nice.
It's probably faster than the PIC18F2550, but I can't say for certain.

**Comment by mafheldt** [comment]
Franz,

Congratulations!!! - there is nothing like kids to occupy every waking -
and sleeping! - moment.

The problem with the thread in WxWidgets is that although it was specified
to run on interrupt/realtime when it waited for the USB response from the
PIC it would wait 50ms (I spent some time trying to get around that in
2013).
I got around that but changing the protocol to send multiple 64 byte
packets to the programmer before expecting a response - that sped things up
greatly - BUT I only did it for the dsPICs/PIC24s as they were the only big
chips back then.

The PIC was not a big problem, but I sped up the programming by tweaking
the bit bang code and pretty well maxed out the programming speed. In my
email I sent I said it was 6 times faster overall - I don't remember if
that code was ever pulled into the system code, but it must still be in my
github clone of the code.

I am pretty sure that the limit at this point is the programming protocol
to the target PIC. Microchip added an "executive" are to many of the large
chips where it downloads a program, that then reads only the data from the
programmer (the current protocol is actually sending instructions and data
to the target PIC) and this would speed it up greatly

Of course these days one can buy a pickit 3 for 10 EUR on ebay.

mike

**Comment by fransschreuder** [comment]
True, because of the price of the chinese programmers, and the availability of mplabx for linux, usbpicprog has lost quite some relevance.

**Comment by mafheldt** [comment]
I have a pickit 3, mplabx is pretty crappy - but it does have breakpoints,
but I still use my usbpicprog!
I am right now updating my solar power charger for my boat and I'm using
your usbpicprog, it was a great little product

all the best
mike
